### ISSUE TITLE
Deepslate/stone variants for both ores

### ISSUE THREAD

**Issue by Helpbot3000** [andersblomqvist/sulfur-potassium-mod#11]
For parity with vanilla, both sulfur and potassium should have both stone and deepslate ores even if they do not naturally generate.

**Comment by andersblomqvist** [comment]
I don't see why that would be necessary due to I've purposely made sulfur only spawn at deepslate levels while potassium in regular stone.  It would just create more files which are never used.

**Comment by Helpbot3000** [comment]
> I don't see why that would be necessary due to I've purposely made sulfur only spawn at deepslate levels while potassium in regular stone. It would just create more files which are never used.

Just to keep in line with the way Vanilla handles ores.  All ores have deepslate and stone variants just for consistency.

**Comment by andersblomqvist** [comment]
With that logic there would be stone and deepslate variants for all the nether ores. I will keep them separated.
