### ISSUE TITLE
Question about update

### ISSUE THREAD

**Issue by vico93** [andersblomqvist/sulfur-potassium-mod#19]
Hi! Do you still have intention to update this mod to 1.20.6/1.21?

**Comment by andersblomqvist** [comment]
There is currently no plan of doing an update.

**Comment by vico93** [comment]
> There is currently no plan of doing an update.

Can others fork the repository to update themselves?

**Comment by andersblomqvist** [comment]
Yes of course!

**Comment by vico93** [comment]
@Khazoda sorry the totally random ping, but would you have interest in update this? This mod seems similar in mechanics to your [Bronze](https://github.com/Khazoda/bronze) mod, both in an amazing vanilla-friendly way, so i thought you could have interest as well.

**Comment by NepNep21** [comment]
> Yes of course!

Can you clarify whether that means you would like the changes sent in a PR or as a completely separate project?

**Comment by andersblomqvist** [comment]
@NepNep21 A PR is the way to go. Merge into either fabric or forge branch

**Comment by andersblomqvist** [comment]
@NepNep21 I've updated this repo by renaming `master` branch to `fabric` and merged some open PRs. Just a reminder to update your fork if you decide to do anything.

**Comment by andersblomqvist** [comment]
@vico93 The mod has been updated to Fabric 1.21, see modrinth or curseforge for download.

I will close this issue now even though 1.20.6 version is missing.

**Comment by vico93** [comment]
Thanks a lot @andersblomqvist and @NepNep21 !!!
